
version: '3.7'
services: 
   
    eureka-server:
        image: eureka-server
        ports: 
            - "8761:8761"
        restart: always
       
        networks:
            - app-network
    
    product-service:
        image: product-service
        ports: 
            - "5100-5150:5100"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
                
        depends_on:
            - eureka-server
        networks:
            - app-network
 
    coupon-service:
        image: coupon-service
        ports: 
            - "5200-5299:5200"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
        depends_on:
            - eureka-server
        networks:
            - app-network

    cart-service:
        image: cart-service
        ports: 
            - "5000-5099:5000"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
        depends_on:
            - eureka-server
        networks:
            - app-network

    api-gateway-server:
        image: api-gateway-server
        ports: 
            - "8888:8888"
        restart: always
        environment:
            EUREKA_HOST: eureka-server
            EUREKA_PORT: 8761
        depends_on:
            - eureka-server
        networks:
            - app-network
 
# Networks to be created to facilitate communication between containers
networks:
    app-network:  
    
