
version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:876983010549:task-definition/intcde021-coupon-service-taskdfn:1"
        LoadBalancerInfo:
          ContainerName: "coupon-service"
          ContainerPort: "5200"
        PlatformVersion: "LATEST"

